["protostar.config"]
protostar_version = "0.2.5"

["protostar.test"]
disable-hint-validation = true

["protostar.project"]
libs_path = "exercises"

["protostar.contracts"]
main = [
    "exercises/main.cairo",    
]
